{%set name = "docker-py" %}
{%set version = "1.10.5" %}
{%set hash_type = "sha256" %}
{%set hash_val = "bdd6ccefc6221bf7711eac65a0488efb95bd8afb5d993eb7e038237d325724c0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  skip: True  # [win32]
  # win32 requires pypiwin32, which we don't have a build of.
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - requests >=2.11.1
    - six >=1.4.0
    - websocket-client >=0.32.0
    - docker-pycreds  >=0.2.1
    - ssl_match_hostname >=3.5  # [py<35]
    - ipaddress >=1.0.16  # [py<33]
    - pypiwin32 >=219  # [win32]

test:
  imports:
    - docker
    - docker.api
    - docker.auth
    - docker.ssladapter
    - docker.transport.unixconn
    - docker.utils
    - docker.utils.ports

about:
  home: https://github.com/docker/docker-py/
  license: Apache 2.0
  summary: 'Python client for Docker.'

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
