{% set version = "7.1.0" %}

package:
  name: docker-py
  version: {{ version }}

source:
  url: https://github.com/docker/docker-py/archive/{{ version }}.tar.gz
  sha256: 88d2b4271ded68be2abc7db35ceed342ef81804a58c8f4f32fa34f7fdef5f662

build:
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{version}}
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python
    - requests >=2.26.0
    - urllib3 >=1.26.0
    - pywin32 >=304 # [win]
    - paramiko >=2.4.3
    - websocket-client >=1.3.0

test:
  imports:
    - docker
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/docker/docker-py/
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Python client for Docker.
  description: |
    A Python library for the Docker Engine API. It lets you do anything the docker command does, 
    but from within Python apps - run containers, manage containers, manage Swarms, etc.
  dev_url: https://github.com/docker/docker-py/
  doc_url: https://docker-py.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
    - scopatz
    - mariusvniekerk
    - mingwandroid
