{% set version = "1.10.6" %}

package:
  name: docker-py
  version: {{ version }}

source:
  fn: docker-py-{{ version }}.tar.gz
  url: https://github.com/docker/docker-py/archive/{{ version }}.tar.gz
  sha256: dd1aa55dbe507538318e51e5303077d146d5176abd6b05fe9bcde24c289410bc

build:
  skip: True  # [win32]
  # win32 requires pypiwin32, which we don't have a build of.
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - requests >=2.11.1
    - six >=1.4.0
    - websocket-client >=0.32.0
    - docker-pycreds  >=0.2.1
    - ssl_match_hostname >=3.5  # [py<35]
    - ipaddress >=1.0.16  # [py<33]
    - pypiwin32 >=219  # [win32]

test:
  imports:
    - docker
    - docker.api
    - docker.auth
    - docker.ssladapter
    - docker.transport.unixconn
    - docker.utils
    - docker.utils.ports

about:
  home: https://github.com/docker/docker-py/
  license: Apache 2.0
  summary: 'Python client for Docker.'

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
