travis:
  secure:
    BINSTAR_TOKEN: dT41OhEQsgXHWZdsUSsIxZkjAthN8/qs6RVsMrnPteCh/kd+DCrkVgA7JC70hsAwkLsghoq6NT+epEdlRJTewylZ7t6VqYUtZnJ1Xx+oIv65+c9VD1x1dRsIFmo8dN0RPcmSeW72evys6E94PASDoltG9Sx4EKTuYoawzHCTce3hUqGD2EV83bZBWvpPop1fAneBwM0Cuez5FuV0nau0AYWHzt7yGgBfrkeXGmvVqO50CXceI5h8ub0+9OUbn1ivqXSWPPdJSojOf+2EUIB6LJNBPaIIgLzv9IovIoZlfyDzIU//PrDfu+6Trh5RmV2NXfmZAS/1dIuIh7FPFEy74/TAmkZIlgxr8tGq2ZrrXdOEcai60cSLILWqdxaINVHbKQQogOKU7NndJBsg01egGKscRQh8/46bKjIVLE+bou9IoGOucHqdr5MnfA3Oj/HFKI4pW9MoUsdr26/70U7IDzjgT0KQMCLTYysEgVPUmGmmp+rWosQGNmHC0TmOjS+ZmD7Z6fBUHhrkbLnsgvSUGvkzSIXBIv+SLHywC3atAGTEF6BmTAN9q+sQj4B7WK3/GkuwWP0vL58dtWkDhaJ+bC6M+5WXJCgC/Jj1LZKMIu8eSP++j0ijAGuCq7n3qx8Wvu/lStOgMrygHP5mYLPT3M5TxA74ZJ/N0CVluXnBM80=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
